services:
  web:
    build: .
    container_name: bookstore_web
    restart: unless-stopped
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - mongo
      - redis

  celery_worker:
    build: .
    container_name: bookstore_celery_worker
    restart: unless-stopped
    command: python -m celery -A app.core.celery_app.celery_app worker --pool=solo --loglevel=info
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - redis
      - mongo

  celery_beat:
    build: .
    container_name: bookstore_celery_beat
    restart: unless-stopped
    command: python -m celery -A app.core.celery_app.celery_app beat --loglevel=info
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - redis
      - mongo

  mongo:
    image: mongo:7
    container_name: bookstore_mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7
    container_name: bookstore_redis
    restart: unless-stopped
    ports:
      - "6379:6379"

volumes:
  mongo_data: